package test.validationshoppingcar.userinterfaces;

import net.serenitybdd.screenplay.targets.Target;
import org.openqa.selenium.By;

public class CabacerosPage {


    public static final net.serenitybdd.screenplay.targets.Target BTN_COMPRA_PRODUCTO_1 = Target.the("Button of compra rapida of product 1").located(By.xpath("//div[@id='gallery-layout-container']/div[3]/section/a/article/div[2]/div[2]/div/div/div/div[2]/div/div/div[2]/div/div/div/div[@class='button-modal flex items-center vtex-button bw1 ba fw5 v-mid relative pa0 lh-solid br2 min-h-small t-action bg-action-primary b--action-primary c-on-action-primary hover-bg-action-primary hover-b--action-primary hover-c-on-action-primary pointer w-100']"));
    public static final net.serenitybdd.screenplay.targets.Target BTN_COMPRA_PRODUCTO_2 = Target.the("Button of compra rapida of product 2").located(By.xpath("//div[@id='gallery-layout-container']/div[4]/section/a/article/div[2]/div[2]/div/div/div/div[2]/div/div/div[2]/div/div/div/div[@class='button-modal flex items-center vtex-button bw1 ba fw5 v-mid relative pa0 lh-solid br2 min-h-small t-action bg-action-primary b--action-primary c-on-action-primary hover-bg-action-primary hover-b--action-primary hover-c-on-action-primary pointer w-100']"));
    public static final net.serenitybdd.screenplay.targets.Target BTN_COMPRA_PRODUCTO_3 = Target.the("Button of compra rapida of product 3").located(By.xpath("//div[@id='gallery-layout-container']/div[11]/section/a/article/div[2]/div[2]/div/div/div/div[2]/div/div/div[2]/div/div/div/div[@class='button-modal flex items-center vtex-button bw1 ba fw5 v-mid relative pa0 lh-solid br2 min-h-small t-action bg-action-primary b--action-primary c-on-action-primary hover-bg-action-primary hover-b--action-primary hover-c-on-action-primary pointer w-100']"));
    public static final net.serenitybdd.screenplay.targets.Target BTN_COMPRA_PRODUCTO_4 = Target.the("Button of compra rapida of product 4").located(By.xpath("//div[@id='gallery-layout-container']/div[10]/section/a/article/div[2]/div[2]/div/div/div/div[2]/div/div/div[2]/div/div/div/div[@class='button-modal flex items-center vtex-button bw1 ba fw5 v-mid relative pa0 lh-solid br2 min-h-small t-action bg-action-primary b--action-primary c-on-action-primary hover-bg-action-primary hover-b--action-primary hover-c-on-action-primary pointer w-100']"));
    //public static final net.serenitybdd.screenplay.targets.Target BTN_COMPRA_NEW_COMFORT_PEGGASI = Target.the("Button of compra rapida of new comfort king").located(By.xpath("//div[@id='gallery-layout-container']/div[12]/section/a/article/div[2]/div[2]/div/div/div/div[2]/div/div/div[2]/div/div/div/div[@class='button-modal flex items-center vtex-button bw1 ba fw5 v-mid relative pa0 lh-solid br2 min-h-small t-action bg-action-primary b--action-primary c-on-action-primary hover-bg-action-primary hover-b--action-primary hover-c-on-action-primary pointer w-100']"));
    public static final net.serenitybdd.screenplay.targets.Target BTN_COMPRA_PRODUCTO_5 = Target.the("Button of compra rapida of product5").located(By.xpath("//div[@id='gallery-layout-container']/div[8]/section/a/article/div[2]/div[2]/div/div/div/div[2]/div/div/div[2]/div/div/div/div[@class='button-modal flex items-center vtex-button bw1 ba fw5 v-mid relative pa0 lh-solid br2 min-h-small t-action bg-action-primary b--action-primary c-on-action-primary hover-bg-action-primary hover-b--action-primary hover-c-on-action-primary pointer w-100']"));
    //public static final net.serenitybdd.screenplay.targets.Target BTN_COMPRA_NEW_COMFORT_FLOTANTE = Target.the("Button of compra rapida new comfort flotante").located(By.xpath("/html/body/div[2]/div/div[1]/div/div[3]/div/div[9]/section/div[2]/div/div[3]/div/div[2]/div/div/div[5]/div/div/div/div[17]/section/a/article/div[2]/div[2]/div/div/div/div[2]/div/div/div[2]/div/div/div/div/span"));
    public static final net.serenitybdd.screenplay.targets.Target BTN_AGREGAR =Target.the("Button of agregar").located(By.xpath("//div[@class='quick-purchase-modal-container exito-vtex-components-4-x-quickPurchaseModalContainer']/div/div[@class='vtex-flex-layout-0-x-flexCol  ml0 mr0 pl0 pr0      flex flex-column h-100 w-100']/div/div/div/div/div/div/div/div/div[2]/button"));
    public static final net.serenitybdd.screenplay.targets.Target BTN_CERRAR =Target.the("Button of cabeceras").located(By.xpath("//div[@class='exito-vtex-components-4-x-defaultModalHeader']/span"));
    public static final net.serenitybdd.screenplay.targets.Target BTN_ADD_MAS =Target.the("Button of cabeceras").located(By.xpath("//div[@class='exito-vtex-components-4-x-stepperBoard']/button[@class='exito-vtex-components-4-x-buttonActions exito-vtex-components-4-x-productSummaryAddToCar  product-summary-add-to-car-plus']"));
    public static final net.serenitybdd.screenplay.targets.Target TXT_CABECEROS =Target.the("Description of the category").located(By.xpath("//div[@class='flex flex-grow-1 w-100 flex-column']/div[3]/div/div/div/h1"));
    public static final net.serenitybdd.screenplay.targets.Target BTN_SHOPPING_CAR =Target.the("Button of cabeceras").located(By.xpath("//div[@class='vtex-flex-layout-0-x-flexColChild vtex-flex-layout-0-x-flexColChild--header-links pb0']/div/div/div[@class='pr0 items-stretch    flex'][4]/div/a[@class='exito-header-3-x-minicartLink']"));

}
